/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pohl' at '10/20/16 4:33 PM' with Gradle 3.1
 *
 * @author pohl, @date 10/20/16 4:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
